import pandas as pd
from sklearn import decomposition

# Performs PCA reduction to data generated by _featureExtraction
# Saves result in files described below
n_components = 20

print("Eyes feature decomposition: start")
df_X = pd.read_csv('eyes_landmarks_features.csv', sep=',', header=None)
ipca = decomposition.PCA(n_components=n_components)
arr = ipca.fit_transform(df_X.drop(index=0).values)
pd.DataFrame(arr).to_csv("eyes_landmarks_features_dec.csv")
print("Eyes feature decomposition: end")


print("Nose feature decomposition: start")
df_X = pd.read_csv('nose_landmarks_features.csv', sep=',', header=None)
ipca = decomposition.PCA(n_components=n_components)
arr = ipca.fit_transform(df_X.drop(index=0).values)
pd.DataFrame(arr).to_csv("nose_landmarks_features_dec.csv")
print("Nose feature decomposition: end")

print("Lips feature decomposition: start")
df_X = pd.read_csv('lips_landmarks_features.csv', sep=',', header=None)
ipca = decomposition.PCA(n_components=n_components)
arr = ipca.fit_transform(df_X.drop(index=0).values)
pd.DataFrame(arr).to_csv("lips_landmarks_features_dec.csv")
print("Lips feature decomposition: end")

print("Face conture feature decomposition: start")
df_X = pd.read_csv('face_conture_landmarks_features.csv', sep=',', header=None)
ipca = decomposition.PCA(n_components=n_components)
arr = ipca.fit_transform(df_X.drop(index=0).values)
pd.DataFrame(arr).to_csv("face_conture_landmarks_features_dec.csv")
print("Face conture feature decomposition: end")